/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nishavaity' at '12/1/16 6:21 PM' with Gradle 3.0
 *
 * @author nishavaity, @date 12/1/16 6:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
